blank_issues_enabled: true
contact_links:
  - name: Forums
    url: https://github.com/MilesCranmer/PySR/discussions
    about: Please ask and answer questions about how to use SymbolicRegression.jl and PySR here.
