name: CI

on:
  push:
    branches:
      - "*"
    paths:
      - "test/**"
      - "src/**"
      - ".github/workflows/**"
      - "Project.toml"
  pull_request:
    branches:
      - master
    paths:
      - "test/**"
      - "src/**"
      - ".github/workflows/**"
      - "Project.toml"
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - "1.6"
          - "1.8"
          - "1"
        os:
          - ubuntu-latest
          - macOS-latest
        include:
          - os: windows-latest
            julia-version: "1"

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Cache dependencies"
        uses: julia-actions/cache@v1
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1
      - name: "Run tests"
        run: |
          julia --color=yes -e 'import Pkg; Pkg.add("Coverage")'
          julia --color=yes --threads=auto --check-bounds=yes --depwarn=yes --code-coverage=user -e 'import Coverage; import Pkg; Pkg.activate("."); Pkg.test(coverage=true)'
          julia --color=yes coverage.jl
        shell: bash
      - name: "Coveralls"
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: lcov.info
          parallel: true
          flag-name: julia-${{ matrix.julia-version }}-${{ matrix.os }}-${{ github.event_name }}

  coveralls:
    name: Indicate completion to coveralls
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Finish
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
